### ISSUE TITLE
Can anyone explain how tutum-agent works?

### ISSUE THREAD

**Issue by resouer** [tutumcloud/tutum-agent#15]
I am a active user of tutum, but I have some security concerns about installing a agent on my host (it's my personal PC), so I wonder if anyone can explain **what the tutum-agent did** on my PC? Does it expose any security issue to the outside world?

And I also noticed there's a public IP like `183.129.190.82` assigned to me, that also worried me a lot.

The final question is that I also have a VM which has **no direct internet access**, can I add it as a tutum node? (Currently I use route forward from another VM with PublicIP to enable that VM access internet)

If you guys can add this part into README, that's will be really helpful!

**Comment by tifayuki** [comment]
tutum-agent does the followings when it starts:

- register to tutum server with token, uuid, and a self-signed certificate.
- run docker daemon on port `2735` with the self-signed certificate and the public cert returned from tutum server. Thus, only tutum server can connect to the docker daemon
- check if port `2735` is accessible from the public network. If not, open a `ngrok` tunnel for tutum to connect to.
- upgrade docker: periodically check if there is a `docker.new` and `docker.new.sig`(the signature of docker.new). If yes, and the author who signs the signature is trusted by the host OS, replace the docker binary and restart docker daemon
- restart docker daemon whenever it dies unexpected.
- Set the nice value of docker daemon to -10, and reset the nice of its child processes.

**Comment by resouer** [comment]
@tifayuki It's so kind of you! Now it's quite clear. Thanks a lot, I can close this issue now.
