### ISSUE TITLE
Not working behind a firewall with incoming port restrictions

### ISSUE THREAD

**Issue by JStumpp** [tutumcloud/tutum-agent#2]
It would be great, if the tutum-agent would work behind firewalls with incoming port restrictions.

**Comment by fermayo** [comment]
We are already working on that ;-) Stay tuned!

**Comment by tifayuki** [comment]
@JStumpp 
We have made tutum-agent work behind firewall, you can give a try :)

**Comment by JStumpp** [comment]
Great, it is working, thanks!
