### ISSUE TITLE
Need help on setting the extra docker daemon flags

### ISSUE THREAD

**Issue by KelvinJin** [tutumcloud/tutum-agent#20]
I notice that we can set the docker daemon flags by using `-docker-opts=...` when starting tutum-agent by `tutum-agent -docker-opts=...`. However, I want to somehow start tutum agent by using `service tutum-agent start`. So the question is whether it's possible to pass the options when using `service tutum-agent start`?

**Comment by tifayuki** [comment]
You can change the start script in `/etc/init.d/tutum.agent`.
In line 17: `exec="/usr/bin/$prog"`, change it to `exec="usr/bin/$prog -opts=<xxx>"` should work

**Comment by KelvinJin** [comment]
It's super weird. Even after I changed the file, the parameters were not passed into the command that got executed. 

When I used `ps aux | grep tutum-agent', I could see that the command being executed was still `/usr/bin/tutum-agent`

**Comment by tifayuki** [comment]
Hi Kelvin,

That change doesn't work on my side either. I think the setting is distro specific

I tried ubuntu 14.04, it works when you edit the file `/etc/init/tutum-agent.conf` in line 35

**Comment by KelvinJin** [comment]
Hey tifayuki,

Thanks for the reply. I'm using a CentOS 7 machine. I finally found that I need to change the content in the `tutum-agent.service` at `/usr/lib/systemd/system/tutum-agent.service`.

The followings are the original content:

```bash
[Unit]
Description=Agent to manage Docker hosts through Tutum
Documentation=https://support.tutum.co/
After=network.target docker.socket
Requires=tutum-agent.socket

[Service]
ExecStart=/usr/bin/tutum-agent
MountType=slave
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity

[Install]
WantedBy=multi-user.target
```

It all went well when i added the `-debug=true` to the `ExecStart` field and I could see the debug flag worked by viewing the log file. However, when I tried to add `-docker-opts="-g /mnt/docker -s btrfs"`, it just failed to start when I used `sudo systemctl start tutum-agent.service`. The error was:

```
tutum-agent.service - Agent to manage Docker hosts through Tutum
   Loaded: loaded (/usr/lib/systemd/system/tutum-agent.service; disabled)
   Active: failed (Result: exit-code) since Tue 2015-08-25 07:35:56 UTC; 5min ago
     Docs: https://support.tutum.co/
  Process: 2800 ExecStart=/usr/bin/tutum-agent -docker-opts="-g /mnt/docker -s btrfs" (code=exited, status=1/FAILURE)
 Main PID: 2800 (code=exited, status=1/FAILURE)

Aug 25 07:35:56 xlabs-analytics-build-node.novalocal tutum-agent[2800]: -tutum-token="": Override 'TutumToken'
Aug 25 07:35:56 xlabs-analytics-build-node.novalocal tutum-agent[2800]: -tutum-uuid="": Override 'TutumUUID'
Aug 25 07:35:56 xlabs-analytics-build-node.novalocal tutum-agent[2800]: set: Set items in the config file and exit, supported items
Aug 25 07:35:56 xlabs-analytics-build-node.novalocal tutum-agent[2800]: CertCommonName="xxx"
Aug 25 07:35:56 xlabs-analytics-build-node.novalocal tutum-agent[2800]: DockerHost="xxx"
Aug 25 07:35:56 xlabs-analytics-build-node.novalocal tutum-agent[2800]: TutumHost="xxx"
Aug 25 07:35:56 xlabs-analytics-build-node.novalocal tutum-agent[2800]: TutumToken="xxx"
Aug 25 07:35:56 xlabs-analytics-build-node.novalocal tutum-agent[2800]: TutumUUID="xxx"
Aug 25 07:35:56 xlabs-analytics-build-node.novalocal systemd[1]: tutum-agent.service: main process exited, code=exited, status=1/FAILURE
Aug 25 07:35:56 xlabs-analytics-build-node.novalocal systemd[1]: Unit tutum-agent.service entered failed state.
```

I don't really think it will help. But the fact is that if I start the tutum-agent using `/usr/lib/tutum-agent -docker-opts=...`, it will work. So i don't understand...There's nothing output in the log file neither...

**Comment by tifayuki** [comment]
Hi Kelvin,

I am not familiar with how the ExecStart is invoked by systemd. but the error message looks like there is not double quotes when invoking tutum-agent, the actually command may be like `/usr/bin/tutum-agent -docker-opts=-g /mnt/docker -s btrfs`, and tutum-agent will print the help message.

I guess you may need to escape double quotes.

**Comment by KelvinJin** [comment]
Hey tifayuki,

Thanks for the patient replay. I did escape the double quotes but it didn't work. I might just use it without the system service command for now.

Appreciated.
