### ISSUE TITLE
error: unable to start a container

### ISSUE THREAD

**Issue by tpaz** [tutumcloud/tutum-agent#26]
arbitrarily happens each time with different containers, so far after running few containers already, bounced into such errors:

"ERROR: <container_name>-1: Cannot start container 
<container_id>: adding interface vetha72b4d1 to bridge docker0 failed: could not find bridge docker0: no such network interface ERROR: Service Start action on '<container_name>' (using '<image_path>') has failed"

(deliberately left the "vetha72..." interface name even though I assume it is just my specific environment virtual network interface).

not sure if it is tutum-agent or weave or whatever bug, but my only interface to the system is tutum-agent so I assume the root cause analysis shall start there.

tutum-agent version: 0.18.1

The problem persist once retrying over and over again on the same container.
The problem sometimes dismissed only when stopping other container(s) (or all of them) and starting again.

**Comment by fermayo** [comment]
It is a docker 1.7.1 bug (https://github.com/docker/docker/issues/14738). We will be upgrading to 1.8 soon so this will hopefully go away.

**Comment by zixia** [comment]
I get too many this error this week. how long shall we wait before upgraded to 1.8?

**Comment by fermayo** [comment]
You can now upgrade to docker 1.8.3 on tutum
