### ISSUE TITLE
memory consumption not reported for debian 8.2 byon

### ISSUE THREAD

**Issue by mckn** [tutumcloud/tutum-agent#38]
I have two nodes hosted at the same provider. The first one is a Debian 8.2 and the second one is a Ubuntu 14.04. The one with ubuntu installed on it reports memory consumption to Tutum but not the one that have Debian 8.2.

How is memory consumption calculated? When I SSH into the nodes and run "free -m" or "top" both of them have about 300MB free memory. The total amount of memory is 2GB. The one with Ubuntu installed on it reports to Tutum that is has around 1.2GB free memory.

Hope you can help me with this! Thanks!

**Comment by tifayuki** [comment]
Hi @mckn 
tutum-agent doesn't report any metrics. Metrics is collected and send to tutum using https://github.com/tutumcloud/metrics, which uses cAdvisor for the metric collection. The issue may have something to do with cAdvisor.

Tutum will be shut down soon, and it successor Docker cloud doesn't have the built-in monitoring function. So I don't think we are going to solve it.

**Comment by mckn** [comment]
Okay, thanks for the quick response. We are going to move to docker cloud asap so then we will find another way to monitor this kind of metrics.
